siteTitle = "a Codekelvin blog"
siteDescr = "I'm a guy who love crafting software, playing games, and singing songs."
siteAuthor = "Mahatthana Kelvin Nomsawadi"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/blog.codekelvin.com"
